<?php

declare(strict_types=1);

namespace Tests\Functional\Runner;

use Paraunit\Configuration\CoverageConfiguration;
use Paraunit\Runner\Runner;
use PHPUnit\Framework\Attributes\Medium;
use Tests\BaseIntegrationTestCase;

#[Medium]
class RunnerWithCoverageTest extends BaseIntegrationTestCase
{
    protected function setup(): void
    {
        parent::setup(); // TODO: Change the autogenerated stub

        $this->configuration = new CoverageConfiguration(true);
    }

    public function testAllGreen(): void
    {
        $this->setTextFilter('ThreeGreenTestStub.php');
        $this->loadContainer();
        /** @var Runner $runner */
        $runner = $this->getService(Runner::class);

        $exitCode = $runner->run();

        $output = $this->getConsoleOutput();
        $this->assertEquals(0, $exitCode, $output->getOutput());
        $this->assertStringNotContainsString('COVERAGE NOT FETCHED', $output->getOutput());

        $resultsOnNewline = PHP_OS_FAMILY !== 'Linux'
            ? '...'
            : PHP_EOL . '...';

        $this->assertOutputOrder($this->getConsoleOutput(), [
            'PARAUNIT',
            'Coverage driver in use',
            $resultsOnNewline,
        ]);
    }

    public function testCacheWarmupSkipped(): void
    {
        $this->setTextFilter('ThreeGreenTestStub.php');
        $this->loadContainer();
        $runner = $this->getService(Runner::class);

        $exitCode = $runner->run();

        $output = $this->getConsoleOutput();
        $this->assertSame(0, $exitCode, $output->getOutput());
        $this->assertOutputOrder($this->getConsoleOutput(), [
            'PARAUNIT',
            'WARNING: PHPUnit coverage cache not enabled',
            'Execution time',
            'Executed: 1 test classes, 3 tests',
        ]);
    }

    public function testCacheWarmupExecuted(): void
    {
        $this->setOption('configuration', $this->getStubPath() . DIRECTORY_SEPARATOR . 'StubbedXMLConfigs/WithCacheDirectory/phpunit.xml.dist');
        $this->setTextFilter('ThreeGreenTestStub.php');
        $this->loadContainer();
        $runner = $this->getService(Runner::class);

        $exitCode = $runner->run();

        $output = $this->getConsoleOutput();
        $this->assertSame(0, $exitCode, $output->getOutput());
        $this->assertOutputOrder($this->getConsoleOutput(), [
            'PARAUNIT',
            'Coverage driver in use',
            'Warming up coverage cache... Done',
            '...',
            'Execution time',
            'Executed: 1 test classes, 3 tests',
        ]);
    }
}
