name: CI

on:
  pull_request: null
  push:
    branches:
      - 1.x
      - 2.x
  schedule:
    - cron: "42 7 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}'

jobs:
  Tests:
    runs-on: 'ubuntu-latest'
    env:
      SYMFONY_DEPRECATIONS_HELPER: disabled
    strategy:
      matrix:
        php:
          - '8.4'
          - '8.5'
        dependencies: ['highest']
        coverage: ['xdebug']
        phpunit: [false]
        include:
          - description: 'PHP 8.5'
            php: '8.5'
          - description: 'PCov'
            coverage: 'pcov'
            php: '8.4'
          - description: 'lowest'
            coverage: 'xdebug3'
            php: '8.4'
            dependencies: 'lowest'

    name: PHP ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}
          ini-values: display_errors=On, display_startup_errors=On, error_reporting=-1, zend.assertions=1
          tools: flex
      - run: composer remove --dev facile-it/facile-coding-standard --no-update
      - name: Configure Composer minimum-stability
        if: matrix.composer-minimum-stability
        env:
          COMPOSER_MINIMUM_STABILITY: ${{ matrix.composer-minimum-stability }}
        run: composer config minimum-stability "$COMPOSER_MINIMUM_STABILITY"
      - name: Require PHPUnit version
        if: matrix.phpunit
        env:
          PHPUNIT_VERSION: ${{ matrix.phpunit }}
        run: composer require phpunit/phpunit "$PHPUNIT_VERSION" --no-update
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer_options }}
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
      - run: vendor/bin/phpunit --check-php-configuration
        if: matrix.dependencies != 'lowest'
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: './coverage.xml'
          fail_ci_if_error: true
  composer:
    runs-on: ubuntu-latest
    name: Composer.json checks
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.4'
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: highest
      - run: vendor/bin/composer-dependency-analyser
      - run: composer validate --strict
  Rector:
    runs-on: ubuntu-latest
    name: Rector
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.4'
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: highest
      - run: vendor/bin/rector --ansi --dry-run
  PHP-CS-Fixer:
    runs-on: ubuntu-latest
    name: Code style
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.4'
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: highest
      - run: vendor/bin/php-cs-fixer fix --ansi --verbose --dry-run
  PHPStan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.4'
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: highest
      - run: vendor/bin/phpstan analyse --ansi
